" Disable cursor blinking in normal mode
"set gcr=n:blinkon0
" Disable cursor blinking in normal and insert mode
set gcr=a:blinkon0

" Hide the toolbar
set guioptions-=T

"set lines=35
set lines=29
set columns=84

" Slightly different from console vim
set showbreak=\ \ \ ↳
